add possibility to modify ControllerBuilder in ControllerCommandConfig
openshift/library-go pull request #1128
Opened 2021-07-06 20:52 UTC by atiratree

It is hard to customize the `StartController` without a possibility to modify the builder. Otherwise it is necessary to copy paste a lot of code: https://github.com/openshift/cluster-policy-controller/pull/65/commits/a94cb90b7397b26d1fc72c2ffaa29d27d41a541e. 

This change would be helpful for https://github.com/openshift/cluster-policy-controller/pull/65/

2021-07-06 20:53 UTC, atiratree commented on pkg/controller/controllercmd/cmd.go
> +func NewControllerCommandConfig(componentName string, version version.Info, startFunc StartFunc, controllerBuilderModifier ControllerBuilderModifier) *ControllerCommandConfig {
is it okay to change the function header?

2021-07-07 13:30 UTC, soltysh requested changes

2021-07-07 13:30 UTC, soltysh commented on pkg/controller/controllercmd/cmd.go
> +type ControllerBuilderOptions struct {
This seems a bit excessive, I'd imagine tweaking only the bits you require see https://github.com/openshift/cluster-policy-controller/commit/a94cb90b7397b26d1fc72c2ffaa29d27d41a541e#r53164748 where I'm pointing only the necessity to translate from one type of config to another, wdyt?

2021-07-08 14:12 UTC, atiratree commented
after a discussion, the default config should be enough for our use case

2021-07-08 14:12 UTC, closed without merging