add conditional resources to the static resource controller
openshift/library-go pull request #1246
Opened 2021-11-15 22:15 UTC by deads2k

@ravisantoshgudimetla had a PR very similar to this with some other stuff layered on top.
@ingvagabund had a PR that has a specific implementation of this for PDBs

I think this is a basis for PDB creation on some topologies and not others by using conditionals.

/assign @ingvagabund

2021-11-16 12:45 UTC, ingvagabund requested changes
Just few nits

2021-11-16 12:45 UTC, ingvagabund commented on pkg/operator/staticresourcecontroller/static_resource_controller.go
> +type ConditionalFunction func() bool
Already there: https://github.com/openshift/library-go/blob/master/pkg/operator/resource/resourceapply/generic.go#L58-L60

2021-11-16 12:45 UTC, ingvagabund commented on pkg/operator/staticresourcecontroller/static_resource_controller.go
> +		case shouldCreate && shouldDelete:
Worth writing a unit test at least for this case.

2021-11-16 12:45 UTC, ingvagabund commented on pkg/operator/staticresourcecontroller/static_resource_controller.go
> +func (c *StaticResourceController) WithConditionalResources(manifests resourceapply.AssetFunc, files []string, shouldCreateFnArg, shouldDeleteFnArg ConditionalFunction) *StaticResourceController {
Worth unit testing this for nil create/delete condition functions they get set to default always true/false.

Possibly reuse https://github.com/openshift/library-go/pull/1110/files#diff-2ba2b98cfb79db1510fd030672e638dac32c02bce52f8238b5c10651fb7ded8d ?

2021-11-16 20:28 UTC, deads2k commented
```
[deads@fedora library-go]$ git push -f
Enumerating objects: 797, done.
Counting objects: 100% (495/495), done.
Delta compression using up to 12 threads
Compressing objects: 100% (132/132), done.
Writing objects: 100% (337/337), 136.92 KiB | 34.23 MiB/s, done.
Total 337 (delta 212), reused 311 (delta 194), pack-reused 0
remote: Resolving deltas: 100% (212/212), completed with 101 local objects.
To github.com:/deads2k/library-go
 ! [remote rejected]     conditional -> conditional (cannot lock ref 'refs/heads/conditional': reference already exists)
error: failed to push some refs to 'github.com:/deads2k/library-go'

```

hmmmm.... problem for tomorrow I guess.

2021-11-17 08:20 UTC, ingvagabund commented
/lgtm

2021-11-17 08:22 UTC, merged