OCPBUGS-2765: don't log openshift tokens
openshift/library-go pull request #1500
Opened 2023-04-14 18:06 UTC by ibihim

# What

Don't log tokenreviews and tokenrequests beyond the metadata level. Even if they belong to the openshift group and not the kubernetes one.

# Why

Some resources exist not only in the upstream groups, but also in the downstream groups. This means that some resources get validates as downstream or upstream resource.
Even though tokens are logged as belonging to the "authentication.k8s.io" group, during validation, they have the "oauth.openshift.io" group.

2023-04-26 17:17 UTC, ibihim commented
/jira refresh

2023-04-26 17:19 UTC, ibihim commented
/jira refresh

2023-04-27 08:20 UTC, ibihim commented
PTAL @openshift/openshift-team-auth

2023-04-27 14:05 UTC, stlaz requested changes

2023-05-04 07:29 UTC, stlaz commented
/lgtm

2023-05-08 11:07 UTC, merged

2023-05-10 08:24 UTC, ibihim commented
/cherrypick release-4.13

2023-05-10 08:33 UTC, ibihim commented
/cherrypick release-4.12

2023-05-10 08:34 UTC, ibihim commented
/cherrypick release-4.11

2023-05-10 08:35 UTC, ibihim commented
/cherrypick release-4.10