Use correct grammatical form
openshift/library-go pull request #1678
Opened 2024-02-15 13:42 UTC by peterroth

Singular if the node count is below 2, plural if more than 1

2024-02-26 21:29 UTC, peterroth commented
Hello @deads2k amd @vrutkovs,
Could you please check this PR? Review was automatically requested but I can see much more activity from you, hence I reach out to you.

2024-02-26 22:44 UTC, vrutkovs requested changes

2024-02-26 22:44 UTC, vrutkovs commented on pkg/operator/staticpod/controller/installer/installer_controller.go
> +		if count > 1 {
```suggestion
nodesStr = "node"
if count > 1 {
    nodesStr = "nodes"
}
revisionStrings = append(revisionStrings, fmt.Sprintf("%d %s is at revision %d", count, nodesStr currentRevision))
```

2024-02-26 22:44 UTC, vrutkovs commented
/ok-to-test

2024-02-27 07:50 UTC, peterroth reviewed
The code snippet is modified with the requested change.

2024-02-27 09:18 UTC, vrutkovs approved these changes
/approve
/lgtm

2024-02-28 14:17 UTC, dgrisonnet approved these changes
/approve

2024-02-28 14:31 UTC, merged